### ISSUE TITLE
Player returning 0 position and duration data in certain circumstances

### ISSUE THREAD

**Issue by jsfsarkis** [ryanheise/just_audio#1418]
**Which API doesn't behave as documented, and how does it misbehave?**
Playing certain audio files on iOS while using LockCachingAudioSource breaks the position and duration streams, making them return 0.

I have not been able to find a link between the audio files that don't work. Most do, some don't. Worth noting that this behavior only happens when using LockCachingAudioSource, any other audio source is fine.

Also worth noting that this only happens when the player is in a playing state, when you pause the player position data returns correctly, whenever you resume it goes back to 0.

**UPDATE**
It seems the issue is happening on links that redirect you multiple times.
In my case, this specific link redirects me 5 times before landing on the original audio file.
The solution I have implemented is to resolve the URLs myself, get the final link, and pass that to the player, instead of passing the link I have and let the player handle the redirects itself.

I can confirm that this solution is working for me now, but it isn't ideal. The player should be able to handle this by itself.

**Minimal reproduction project**
The example. 
Please find below a link to an audio file that causes the above behavior.
```
https://pdst.fm/e/pscrb.fm/rss/p/mgln.ai/e/1390/traffic.megaphone.fm/FLIGHTSTUDIOGROUPLTD4700555365.mp3
```

**To Reproduce (i.e. user steps, not code)**
1. Build the app
2. Run the caching example
3. Play the audio
4. The seekbar is broken because position and duration data is null

**Expected behavior**
The player should return accurate position and duration data.

**Smartphone (please complete the following information):**
 - Device: iPhone 16 Pro Simulator / iPhone 11
 - OS: iOS 18 / iOS 18.3.1

**Flutter SDK version**
Flutter 3.27.3
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.3, on macOS 15.2 24C101 darwin-arm64, locale en-LB)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.97.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

**Comment by HosseinArabbeigi** [comment]
Have the same issue when the caching is not completed yet using LockCachingAudioSource source.
On pause call **positionStreams** emits correct position and by calling resume, position will be 0 again.

**Comment by jsfsarkis** [comment]
> Have the same issue when the caching is not completed yet using LockCachingAudioSource source. On pause call **positionStreams** emits correct position and by calling resume, position will be 0 again.

I have found a workaround.

It seems the issue is happening on links that go through multiple redirects before landing on the original source file. I have tried with links that have 2 redirects, it works fine. 

In my specific case, the link I referenced above in the issue goes through 5 redirects and that's where the player is breaking.

The workaround I have found is to go through the redirects yourself, get the original link, and pass that to the player, instead of letting the player handle the redirects itself because that is breaking it.

**Comment by HosseinArabbeigi** [comment]
I have the same problem without any redirections.

**Comment by jsfsarkis** [comment]
Hey @HosseinArabbeigi yeah me too, it kept happening even after I fixed the redirections. I closed this issue and opened a new one where I detailed the problem that I found that is causing it.

There it is:
https://github.com/ryanheise/just_audio/issues/1425

Apparently the issue with LockCachingAudioSource, as far as I can tell, will break when the audio file response headers don't include an accept-ranges field.

Can you confirm if this is the case for you as well?

**Comment by HosseinArabbeigi** [comment]
Thank you @jsfsarkis, yes we don't have accept-ranges too.
I'll ask to append this header from our backend team and let you know the results.

**Comment by kollerorbyz** [comment]
I have Accept-Ranges: bytes header, not sure about redirections, but I still have the issue.
