### ISSUE TITLE
Add optional index parameter to load()

### ISSUE THREAD

**Issue by moritz-weber** [ryanheise/just_audio#160]
Hi @ryanheise I just started trying the current version of just_audio and wanted to thank you for your great work :)

**Is your feature request related to a problem? Please describe.**
When loading a `ConcatenatedAudioSource` and seeking to a specific index `i` before starting playback, the `currentIndexStream` first propagates `0` and then `i`. This can lead to some ugly UI jumps, if they react to index changes.

**Describe the solution you'd like**
Starting with the specified index would be nice as no "wrong" index would be propagated and no additional handling would be necessary.

**Describe alternatives you've considered**
I could set an index variable in my BackgroundTask and check if the propagated `currentIndex` matches it before setting the currentMediaItem. Seems to be kind of ugly though, as I'd like to have `AudioPlayer` is a single source of truth here.

**Additional context**
Nothing

**Comment by ryanheise** [comment]
That's an interesting one, it sounds like it could be a bug as I did not intend for that behaviour. I will have to investigate. Note that in most cases, it is preferable to use `sequenceStateStream`, although quite possibly the same bug exists in that stream, too.

**Comment by moritz-weber** [comment]
I tried `sequenceStateStream` and it broadcasts `0` as well. The broadcast occurs around line 454 in just_audio.dart:

    _durationFuture = _invokeMethod('load', [source.toJson()]).then(
      (ms) => (ms == null || ms < 0) ? null : Duration(milliseconds: ms));
    final duration = await _durationFuture;

I then lost track in the Java code ;) Hope this helps.

**Comment by ryanheise** [comment]
I have tried to reproduce this, but was unable to. Would you mind providing a reproduction project, and can you tell me if you experienced this on Android or iOS (or both)?

**Comment by moritz-weber** [comment]
I created a minimal project: https://github.com/moritz-weber/just_audio_test
As I encountered the problem with local files (haven't tried the other options), I implemented the local playback here as well.
The paths are just a list of strings, so you would need to fill in paths that exist on your device.
Pressing the play button, triggers the loading, seeking and playback.
The index is only printed to the console, nothing to see in the UI.
I encountered the issue on Android; haven't tried iOS.

**Comment by ryanheise** [comment]
Thanks! I'll look into it now.

**Comment by ryanheise** [comment]
After trying your example, I now have a better understanding of your use case. Currently `load` does indeed load index 0 first before the seek occurs and I agree it would be a useful feature to have initial seek parameters on `load`. In the meantime, you can probably do something like this:

```dart
player.currentIndexStream.skipWhile((i) => i ?? 0 == 0).listen(...);
```

**Comment by moritz-weber** [comment]
Thanks for investigating this. I'll probably do nothing about it for now, as I am the only user of my app and don't really bother about the small glitch it causes ;)

**Comment by halldorlogi** [comment]
> After trying your example, I now have a better understanding of your use case. Currently `load` does indeed load index 0 first before the seek occurs and I agree it would be a useful feature to have initial seek parameters on `load`. In the meantime, you can probably do something like this:
> 
> ```dart
> player.currentIndexStream.skipWhile((i) => i ?? 0 == 0).listen(...);
> ```

I'd really appreciate a feature in that direction.

**Comment by ReaganRealones** [comment]
Hello, I also ran into this issue. I am working on a music streaming app where a user can tap to play a song in an album. So i load the album songs but run into exactly the same thing, it first plays the first song first then jumps to the one. Would be really helpful, setting an index to play would be really helpful :)

**Comment by ReaganRealones** [comment]
> After trying your example, I now have a better understanding of your use case. Currently `load` does indeed load index 0 first before the seek occurs and I agree it would be a useful feature to have initial seek parameters on `load`. In the meantime, you can probably do something like this:
> 
> ```dart
> player.currentIndexStream.skipWhile((i) => i ?? 0 == 0).listen(...);
> ```

Problem with this is, what if the user taps on the very first song? This would cause the app not to update state for the first song

**Comment by ryanheise** [comment]
How about this:

```dart
player.currentIndexStream.skipWhile((i) => i ?? 0 != initialSeekIndex).listen(...);
```

**Comment by ReaganRealones** [comment]
Yeah, I think this is okay. Just hope playing the first song at index 0 before reverting to the set index always isnt at all expensive , is it?


Also i saw the `useLazyPreparation` property on `ConcatenatingAudioSource` , unable to figure out what it possibly does?

**Comment by ryanheise** [comment]
> Yeah, I think this is okay. Just hope playing the first song at index 0 before reverting to the set index always isnt at all expensive , is it?

Yes, I would expect it to be slower since you have to first await `load()` and then you have to await `seek()`. So it would definitely be better if I were to add this feature natively in the plugin.

`useLazyPreparation` currently has an effect only on Android. It is passed through to the similarly-named feature in ExoPlayer which is documented as follows:

> useLazyPreparation - Whether playlist items are prepared lazily. If false, all manifest loads and other initial preparation steps happen immediately. If true, these initial preparations are triggered only when the player starts buffering the media.

**Comment by ryanheise** [comment]
I've just implemented this feature in the latest commit on the master branch:

```dart
await player.load(source, initialIndex: 2, initialPosition: Duration(seconds: 40));
```

By default, the initial index and position will both be zero. Let me know if you notice any issues, and if not I'll put out a release.

Also included in this commit is the ability to call `play()` before `load()` which puts the player into the `playing` state (i.e. play when ready) while the audio source is loading, and will result in the audio playing as soon as the load completes and sufficient audio has buffered (similar to the way that `playing` remains true while a seek is in progress). The only concern with doing this is whether you hear a little bit of the audio from time zero before it repositions itself to `initialPosition`. I didn't notice that in my own testing, though.

**Comment by moritz-weber** [comment]
Thanks for your work. `play` before `load` works great and the additional parameters saved me a few lines.
Unfortunately the initial issue still persists: When listening to `sequenceStateStream` the first broadcast index is still 0.

**Comment by ryanheise** [comment]
I agree it would be better not to have to do this. Looking at the code, I think `currentIndexStream` should emit the correct value for your use case, and if it doesn't, then maybe the platform side of the plugin is doing something unintended.

**Comment by moritz-weber** [comment]
Yes, this does the trick. Thanks :+1:
