### ISSUE TITLE
Seek not working for AAC files on Android

### ISSUE THREAD

**Issue by kbanta11** [ryanheise/just_audio#333]
**Which API doesn't behave as documented, and how does it misbehave?**
`seek` while playing starts `aac` file types from the beginning when playing on Android (`mp4` and `mp3` files seem to seek correctly. On iOS, all 3 file types seem to work properly). It does seem to update the new position of the file (verified by checking the `player.position` after `seek`, but then seems to actually start playing the audio from the beginning.

**To Reproduce (i.e. user steps, not code)**
File which works: https://firebasestorage.googleapis.com/v0/b/flutter-fire-test-be63e.appspot.com/o/YPWVRFe9M4hBSqSa3yFDaClH60K2%2F2021-03-05_12%3A43%3A34.468423?alt=media&token=efbc7f56-0649-408e-b685-cdf8fe759a41 (mp4)

File which starts over and doesn't work: https://firebasestorage.googleapis.com/v0/b/flutter-fire-test-be63e.appspot.com/o/cgMPHfB6v3T9sKf5c4rrPIOSzrQ2%2F2021-03-03_20%3A55%3A29.433591?alt=media&token=f773214b-3a59-4020-a696-3bd32b34cd07

I've tried testing a few different files of each type, and I think I've narrowed it down to just being the `aac` files when played on Android that have trouble with seeking.

**Expected behavior**
The audio should play from the new updated position.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android

**Comment by ryanheise** [comment]
Hi @kbanta11 this is not the fault of the player, it's just that the player needs a seek table to be able to seek. Try re-encoding the file in a container format that includes a seek table. See:

https://askanydifference.com/difference-between-aac-and-m4a/

**Comment by kbanta11** [comment]
Hmm.. interesting. So I am trying to switch from the `audioplayers` plugin (since this plugin is much more robust and actually is actively maintained (THANK YOU!)), which I think also uses ExoPlayer. With `audioplayers`, I could properly seek on these file types. The main problem is that I need the files to be playable and recordable on both Android and iOS (users generate these recordings) and so far the only combination I've found to work (or used to work with `audioplayers`) is recording `mp4` (not m4a, they seem to be uploaded to firebase as `video/mp4` files though they are just audio) on Android and recording `aac` on iOS, which then both filetypes will play cross platform.

Is there any known way to handle cross-platform audio recording and playing that would enable seek?  Also, since I have many existing user-generated audios, I'm not sure re-encoding all files is possible (I've tried ffmpeg in the past to no avail and had to delete all old files that weren't compatible, though the app was not in use then so it wasn't a big deal).  Any ideas for how to convert these files if needed to a format which will work?

**Comment by kbanta11** [comment]
So after looking through the `audioplayers` code, it looks like on Android it actually uses the android MediaPlayer, which can appears able to seek on `aac` files, so this might be a limitation of ExoPlayer on Android

**Comment by ryanheise** [comment]
Here is the ExoPlayer response:

> We may add approximate seeking using a constant bitrate assumption, at some point in the future.
> 
> That said, if you need seeking, you should really be using a container format that's better able to support it (e.g. MP4).

So the best we can do without using a proper container that contains a seek table is to do "approximate" seeking assuming a constant bitrate. I can consider adding support for that, since ExoPlayer has since added support for this.

However, note as per the ExoPlayer response that you are still better off encoding your audio file in an appropriate format for seeking. I've just tested opening your file in Firefox/Linux and it also failed to seek your file, so I don't think it is a reliable expectation that seeking should work with raw AAC data that contains no seek lookup information.

**Comment by kbanta11** [comment]
Ok. I think the bitrate solution would hopefully work since I'm recording at a constant bitrate (16000). What's interesting is that I'm recording the files on iOS as `kAudioFormatMPEG4AAC`, though the extension was `aac`, so it might have not been recognizing the file as an mp4 encoded aac due to the file extension. I'm trying to change the file extension to `mp4` for new recordings (and will maybe have to go through and manually find old `aac` extension files to convert if this works. I'm not able to play the local files I record to test this right now though, due to `setFilePath` failing due to `no host specified`. I didn't get as much time as I was hoping to look into this today. I should have more time tomorrow to take a closer look and break down what behavior I'm seeing in what scenarios.  As suspected with this being a file format/ExoPlayer issue, I do still get this issue on Android only in the example project with my files.  Will hopefully have more to add tomorrow, sorry for the delay on the extra information! Thank you for looking into this!  Let me know if there are specifics you need from me or what I can do to make this as easy as possible?

**Comment by kbanta11** [comment]
Ok, so I've figured out a setup that is properly recording the files in a way that both android and iOS can seek. Seeking with assumed constant bitrate would still be a nice feature, but at least I can move forward and just start going through the process of converting old files to re-encode them, so this isn't as blocking for me right now. I am still unable to play the files while they're still just locally on the device (I know the file records as I can still upload the file and play it back, just can't play it as a local file due to `setFilePath` failing with this error: 
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): No host specified in URI file:///private/var/mobile/Containers/Data/Application/2303D68B-3BD8-4EC4-9FF2-3601984CEFE7/tmp/20970516-34e3-45a0-b36d-93bf622bcad0.mp4
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2425:9)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2346:48)
#2      _proxyHandlerForUri.handler (package:just_audio/just_audio.dart:2328:46)
#3      _proxyHandlerForUri.handler (package:just_audio/just_audio.dart:2327:23)
#4      _ProxyHttpServer.start.<anonymous closure> (package:just_audio/just_audio.dart:1412:16)
#5      _ProxyHttpServer.start.<anonymous closure> (package:just_audio/just_audio.dart:1408:20)
#6      _rootRunUnary (dart:async/zone.dart:1362:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
```

The one thing that I can think of that this might be is because I'm creating multiple AudioPlayer instances, which I'm not sure if this causes any problems with this plugin? (As I have a main AudioPlayer attached to an AudioService, and then have some files that I want to play after recording as local files independently from the main AudioService/AudioPlayer).

**Comment by ryanheise** [comment]
This sounds like the proxy is being activated erroneously. Are you using headers or a user agent or a caching audio source?

**Comment by kbanta11** [comment]
> This sounds like the proxy is being activated erroneously. Are you using headers or a user agent or a caching audio source?

I'm setting a user agent when creating the AudioPlayer, but am not using headers or a caching audio source. Should I be using a different AudioPlayer initialization for local files?

**Comment by ryanheise** [comment]
This is erroneous behaviour, so there's a bug that needs to be fixed. But until then you can work around it by using a separate player for local files that doesn't have a user agent.

**Comment by kbanta11** [comment]
Yes! After testing this a bit, it does seem removing the user agent fixes this issue. You are an absolute legend! Thank you!

**Comment by ryanheise** [comment]
I've just fixed the proxy+user_agent bug in the latest 0.7.1 release which means you will not need to create a separate `AudioPlayer` instance just for files.

**Comment by ThorgeL** [comment]
@kbanta11 Would you mind sharing with me how you implemented that? Are you using flutter_sound to record the files?

> so I've figured out a setup that is properly recording the files in a way that both android and iOS can seek

I am facing the exact same issue with not being able to seek on Android in the AAC format.

**Comment by kbanta11** [comment]
> not being able to seek on Android in the AAC format

So I still can't seek on `.aac` files, but I can seek on `mp4` files which can be recorded on both. I'm not using `flutter_sound`, but the `sounds` package, which is a fork of `flutter_sounds` and has diverged a little bit from `flutter_sounds`. Using the `sounds` package, I had to create a custom `MediaFormat` so that the files recorded on both android and iOS are saved as `.mp4`.  This is the custom media format that I created and am using:
```
class CustomMediaFormat extends NativeMediaFormat {
  /// ctor
  const CustomMediaFormat({
    int sampleRate = 16000,
    int numChannels = 1,
    int bitRate = 16000,
  }) : super.detail(
    name: 'aac',
    sampleRate: 16000,
    numChannels: 1,
    bitRate: 16000,
  );

  @override
  String get extension => 'mp4';

  // Whilst the actual index is MediaRecorder.AudioEncoder.AAC (3)
  @override
  int get androidEncoder => 3;

  /// MediaRecorder.OutputFormat.MP4
  @override
  int get androidFormat => 2;

  /// kAudioFormatMPEG4AAC
  @override
  int get iosFormat => 1633772320;
}
```

**Comment by zhangruiyu** [comment]
Hope to solve this problem as soon as possible, crying, please help us

**Comment by zhangruiyu** [comment]
@ryanheise Is there any good solution to this problem

**Comment by ryanheise** [comment]
Only what is mentioned above.

A workaround: encode your audio in a file format that is designed for seeking.
A solution: involves adding a feature to just_audio itself to estimate the seek table when it is absent in the file, based on a constant bitrate approximation.

**Comment by zhangruiyu** [comment]
> Only what is mentioned above.
> 
> A workaround: encode your audio in a file format that is designed for seeking.
> A solution: involves adding a feature to just_audio itself to estimate the seek table when it is absent in the file, based on a constant bitrate approximation.

So should I wait for someone to fix this now, or switch to MP3? My technique is very poor, so I can't help you solve the problem

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/112932005-c5171400-914f-11eb-89be-cd9812cd5f76.png)
Try using Constantbitreseeking, and it seems to have worked out for me

**Comment by zhangruiyu** [comment]
> @kbanta11 Would you mind sharing with me how you implemented that? Are you using flutter_sound to record the files?
> 
> > so I've figured out a setup that is properly recording the files in a way that both android and iOS can seek
> 
> I am facing the exact same issue with not being able to seek on Android in the AAC format.

Try using Constantbitreseeking

**Comment by yy1300326388** [comment]
My file is the problem
[4ac610135444863a81504f14f4dd8f00_1621912964634.aac.zip](https://github.com/ryanheise/just_audio/files/6537190/4ac610135444863a81504f14f4dd8f00_1621912964634.aac.zip)

**Comment by yy1300326388** [comment]
@zhangruiyu  Works for me

**Comment by rupakswadesh** [comment]
@zhangruiyu 
thanks, this work for me.

**Comment by ThorgeL** [comment]
> ![image](https://user-images.githubusercontent.com/10591822/112932005-c5171400-914f-11eb-89be-cd9812cd5f76.png) Try using Constantbitreseeking, and it seems to have worked out for me

@zhangruiyu 

I am not sure how to get this to work. It seems like a java file from the Android play dependency is being changed. Do I need to fork just_audio?

**Comment by ryanheise** [comment]
You could fork or just clone to make this modification.

In terms of adding an option to just_audio officially, the delay is that I haven't committed to an API design yet. If it is possible to detect whether an arbitrary file has a seek table or uses VBR, I'd want to use that information to automatically choose the appropriate seek method, but as yet I haven't been able to find any way of doing that in ExoPlayer. I've created an issue on the ExoPlayer project here: https://github.com/google/ExoPlayer/issues/9408 .

Even if I don't go with an API that tries to automatically choose a seek method, I still think it would be essential for an app to query an audio file regarding these properties in order to choose the most appropriate seek method dynamically, because many apps are not in control of which audio files their users may choose to open, and the app must be able to seek correctly for any arbitrary file.

**Comment by ThorgeL** [comment]
Thanks @ryanheise, it works now. I also upvoted your issue on the ExoPlayer project.

**Comment by yanivshaked** [comment]
In case anyone needs a forked version of `just_audio` that uses the above suggested change, you can use:

```
  just_audio:
    git:
      url: https://github.com/12Tech12/just_audio.git
      ref: "13d55fb"
      path: "just_audio"
```

We will keep this fork updated until an option is added officially.

**Comment by lqmminh** [comment]
@ryanheise please check this solution and update to package <3

**Comment by ryanheise** [comment]
@lqmminh this is just a workaround, not a general solution that I can publish until there is a way for ExoPlayer to detect the properties of the file that can help to decide which seek algorithm to apply in each case. My previous comment explains this. Please take a look at the ExoPlayer issue I linked to.

**Comment by ryanheise** [comment]
OK, after reading through the ExoPlayer code, I can see how it is selecting the seeking algorithm. It looks to be entirely harmless for just_audio to automatically enable constant bitrate seeking always.

What happens if I do this is that just_audio will still use more accurate seek algorithms when available, but will fallback to constant bitrate seeking when nothing better is available.

The situation is different for indexed-based seeking, so I will still need to present an API in just_audio for nabling that one, while just always enabling the constant bitrate seeking flag.

**Comment by ryanheise** [comment]
FYI I have just implemented the constant bitrate fallback on the `minor` branch. There is no API change, it is just automatically handled and should hopefully fix the issue with seeking both AAC files as well as any other formats that don't include a seek table. Note that this is an approximate form of seeking, so not as good as where you encode the file with a seektable.

**Comment by ryanheise** [comment]
I'll close this now that the fix has been published.
