### ISSUE TITLE
Permanently empty sequence state when providing an initially empty ConcatinatingAudioSource

### ISSUE THREAD

**Issue by suragch** [ryanheise/just_audio#446]
**Which API doesn't behave as documented, and how does it misbehave?**

I'm initializing the audio player with an initially empty audio source list like so:

```dart
final _player = AudioPlayer();
final _playlist = ConcatenatingAudioSource(children: []);

Future<void> _init() async {
  try {
    await _player.setAudioSource(_playlist);
  } catch (e) {
    print("Error: $e");
  }
}
```

Later I add items to the playlist via audio_service's `addQueueItems` method:

```dart
@override
Future<void> addQueueItems(List<MediaItem> mediaItems) async {
  // manage Just Audio
  final audioSource = mediaItems.map(_createAudioSource);
  _playlist.addAll(audioSource.toList());

  // notify system
  final newQueue = queue.value..addAll(mediaItems);
  queue.add(newQueue);
}

UriAudioSource _createAudioSource(MediaItem mediaItem) {
  return AudioSource.uri(
    Uri.parse(mediaItem.extras!['url']),
    tag: mediaItem,
  );
}
```

Everything (play, pause, seek, skip, repeat, etc) was working until I got to shuffle. When I try to listen to the `sequenceStateStream`, the `effectiveSequence` is always null or empty.

```dart
void _listenForSequenceStateChanges() {
  _player.sequenceStateStream.listen((SequenceState? sequenceState) {
    final sequence = sequenceState?.effectiveSequence;
    final indices = sequenceState?.shuffleIndices;
    print('effective sequence: $sequence, indices: $indices');
    if (sequence == null || sequence.isEmpty) return;
    print('This line is never reached.');
    final items = sequence.map((source) => source.tag as MediaItem);
    queue.add(items.toList());
  });
}
```

**Minimal reproduction project**

This is a little beyond the example, but it is the actual repo I plan to use for my Audio Service tutorial:

- https://github.com/suragch/flutter_audio_service_demo/blob/master/final/lib/services/audio_handler.dart

**To Reproduce (i.e. user steps, not code)**
1. Run the demo app
2. Look at the print logs in the debug console:

```
flutter: effective sequence: null, indices: null
flutter: effective sequence: [], indices: []
flutter: effective sequence: [], indices: [0, 2, 1]
```

**Error messages**

If you press the shuffle button you'll get the following error:

```
Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
```

**Expected behavior**

I would expect the `SequenceState.effectiveSequence` (and `SequenceState.sequence`) to get updated with the current sequence values. I would also expect `effectiveSequence` and `sequence` to have the same length as `shuffleIndices`. However, `shuffleIndices` has the correct length and values while `effectiveSequence` and `sequence` are empty.

This appears to be related to using an empty playlist in the beginning (because my shuffling works with my [previous tutorial](https://medium.com/flutter-community/managing-playlists-in-flutter-with-just-audio-c4b8f2af12eb) where I used a hard-coded playlist). There may be some combination of setting `preload` to false and calling `load` later on, but the solution isn't intuitively obvious. Just approaching the API as a non-expert it would make more sense to be able to set an empty playlist.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser N/A

**Smartphone (please complete the following information):**
 - Device: Android Pixel 4 emulator, iPhone 12 Pro Max simulator
 - OS: Android 11, iOS 14.5

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (4 available)
```

**Additional context**

**Comment by ryanheise** [comment]
This should be fixed in the `fix/load_empty_playlist` branch. Can you try it and let me know?

**Comment by suragch** [comment]
Hmm, I'm still getting the same results with version 0.9.2. The `shuffleIndices` is a list of three values while `sequence` is an empty list. That results in a `RangeError` when trying to get `effectiveSequence`. 

Should I make a more compact project to just demonstrate the error?

**Comment by ryanheise** [comment]
I think I've found the bug, but will need to fix it after sleep.

However, you may also be able to work around it since it's happening when you update the playlist before `_player.setAudioSource()` has actually completed. It will of course be better if I fix the bug, though.

**Comment by ryanheise** [comment]
Can you try the `fix/add_before_load` branch and let me know if it fixes it?

**Comment by suragch** [comment]
Sorry, I seem to have forgotten how to depend on an unpublished branch. Could you tell me how to do that again?

This is what I tried:

```yaml
  just_audio:
    git:
      url: https://github.com/ryanheise/just_audio.git
      ref: fix/add_before_load
```

> pub get failed (1; Could not find a file named "pubspec.yaml" in https://github.com/ryanheise/just_audio.git
b983ba52bb28d9aad6d4b7fc2c212575757c7e8b.)

**Comment by suragch** [comment]
Wait, I got it:

```yaml
  just_audio:
    git:
      url: https://github.com/ryanheise/just_audio.git
      ref: fix/add_before_load
      path: just_audio
```

**Comment by suragch** [comment]
This is working! I've tested Android, iOS, macOS and web. 

(I am getting an uncaught RangeError on web during startup but this might be unrelated to the issue here. It also doesn't affect normal app function. I'll open a new issue in the future if it's a problem.)

Thank you very much! I'll update the tutorial when you've published the update.

**Comment by ryanheise** [comment]
Excellent! I've just published 0.9.3.
